# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bio-isoelectric_point"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George Githinji", "Pascal Betz"]
  s.date = "2012-03-01"
  s.description = "A bioruby plugin for calculating the isoelectric point of a protein "
  s.email = "georgkam@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bio-isoelectric_point.gemspec",
    "lib/bio-isoelectric_point.rb",
    "lib/isoelectric_point/aa.rb",
    "lib/isoelectric_point/extensions.rb",
    "lib/isoelectric_point/pka_data.rb",
    "test/aa_test.rb",
    "test/extensions_test.rb",
    "test/helper.rb",
    "test/test_bio-isoelectric_point.rb"
  ]
  s.homepage = "http://github.com/georgeG/bioruby-isoelectric_point"
  s.licenses = ["Ruby"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "A bioruby plugin for calculating the isoelectric point and the charge of a protein sequence."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, ["~> 2.11.3"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.22"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<bio>, [">= 1.4.2"])
    else
      s.add_dependency(%q<shoulda>, ["~> 2.11.3"])
      s.add_dependency(%q<bundler>, ["~> 1.0.22"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<bio>, [">= 1.4.2"])
    end
  else
    s.add_dependency(%q<shoulda>, ["~> 2.11.3"])
    s.add_dependency(%q<bundler>, ["~> 1.0.22"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<bio>, [">= 1.4.2"])
  end
end

